name: veggieday_ituv
description: IT.UV//Veggieday Project (BBS)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  flutter_login: ^3.2.0
  font_awesome_flutter: ^9.1.0
  cloud_firestore: ^3.1.18
  intl: ^0.17.0
  multiple_stream_builder: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/ituvshort.png
    - assets/images/ituvlong.png
