// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDouCdp9KRygVJgL1fG5OcCFEC82ltz4N8',
    appId: '1:717211038294:web:4e16123a9ec50d079401f7',
    messagingSenderId: '717211038294',
    projectId: 'veggieday-ituv',
    authDomain: 'veggieday-ituv.firebaseapp.com',
    storageBucket: 'veggieday-ituv.appspot.com',
    measurementId: 'G-B9QZZ2PBLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaz3v8kh8mUqW_QVChpPi1xtU2QMxrk_Q',
    appId: '1:717211038294:android:480d60821810aae59401f7',
    messagingSenderId: '717211038294',
    projectId: 'veggieday-ituv',
    storageBucket: 'veggieday-ituv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFOEh6cwnJ4CJv5XB6Ij5VdKKvUm7A20g',
    appId: '1:717211038294:ios:2d29f14f5b991e8c9401f7',
    messagingSenderId: '717211038294',
    projectId: 'veggieday-ituv',
    storageBucket: 'veggieday-ituv.appspot.com',
    iosClientId: '717211038294-9038pd21pekiupip3cgfqr2vfpum142v.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloItuv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFOEh6cwnJ4CJv5XB6Ij5VdKKvUm7A20g',
    appId: '1:717211038294:ios:2d29f14f5b991e8c9401f7',
    messagingSenderId: '717211038294',
    projectId: 'veggieday-ituv',
    storageBucket: 'veggieday-ituv.appspot.com',
    iosClientId: '717211038294-9038pd21pekiupip3cgfqr2vfpum142v.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloItuv',
  );
}
